### PR TITLE
Convert einspline code from C to C++

### PR DESCRIPTION
**Pull request by markdewing**
All the miniapp is now C++ code.

### CODE REVIEW

**Comment by ye-luo** [comment]
@markdewing Could you list what platforms and compilers you have checked?

**Comment by markdewing** [comment]
Just g++ on linux. Do you expect problems on other platforms/compilers?

**Comment by prckent** [comment]
More CI needed...

**Comment by grahamlopez** [comment]
In progress - from multiple angles

**Comment by grahamlopez** [comment]
@ye-luo may merge whenever he is comfortable with it

**Comment by ye-luo** [comment]
I will check a few more platforms and compilers. If they are all fine, I will get it merged. Probably on Monday.

**Comment by ye-luo** [comment]
Checked XL, Intel, GNU and Clang.

**Comment by ye-luo** [comment]
@markdewing 
Can we remove the following files?
./src/Numerics/Einspline/bspline_create.c
./src/Numerics/Einspline/multi_bspline_create.c
./src/Numerics/Spline2/einspline_allocator.c

**Comment by markdewing** [comment]
Yes, the *.c files can be removed.

**Comment by ye-luo** [comment]
Please submit a new PR to clean up the left c files.

**Pull request merged**
