### PR TITLE
Add fine/coarse timer levels

### PR DESCRIPTION
**Pull request by mdewing**
Set the wavefunction components to the 'fine' timer level.

Add the -t command line option to set the level (fine/coarse) and set the default to 'fine'.

Add a structure that can associated different timer levels with the timer list. Also add the associated creation function.

### CODE REVIEW

**Comment by mdewing** [comment]
Output with '-t coarse'
```
Stack timer profile
Timer                 Inclusive_time  Exclusive_time  Calls       Time_per_call
Total                    1.8613     1.1830              1       1.861272161
  Diffusion              0.3267     0.0029              2       0.163332346
    Accept move          0.0012     0.0012            404       0.000003092
    Current Gradient     0.0005     0.0005            768       0.000000675
    Kinetic Energy       0.0002     0.0002              2       0.000100269
    Make move            0.0492     0.0492            768       0.000064056
    Move done            0.0002     0.0002              2       0.000122051
    New Gradient         0.1656     0.1656            768       0.000215598
    Set active           0.0493     0.0493            768       0.000064149
    Update               0.0575     0.0575            404       0.000142437
  Initialization         0.0822     0.0822              1       0.082224116
  Pseudopotential        0.2694     0.0014              2       0.134713471
    Make move            0.0590     0.0590            960       0.000061436
    Value                0.2091     0.2091            960       0.000217770
```

Output with '-t fine' (default) (this run also has -j specified)
```
Stack timer profile
Timer                           Inclusive_time  Exclusive_time  Calls       Time_per_call
Total                              1.8014     1.0995              1       1.801400344
  Diffusion                        0.3365     0.0026              2       0.168253028
    Accept move                    0.0013     0.0013            404       0.000003147
    Current Gradient               0.0022     0.0017            768       0.000002916
      Determinant                  0.0001     0.0001            768       0.000000112
      OneBodyJastrow               0.0002     0.0002            768       0.000000234
      ThreeBodyJastrow             0.0001     0.0001            768       0.000000176
      TwoBodyJastrow               0.0002     0.0002            768       0.000000217
    Kinetic Energy                 0.0002     0.0001              2       0.000092837
      Determinant                  0.0000     0.0000              2       0.000000219
      OneBodyJastrow               0.0000     0.0000              2       0.000017654
      ThreeBodyJastrow             0.0000     0.0000              2       0.000022971
      TwoBodyJastrow               0.0000     0.0000              2       0.000022850
    Make move                      0.0492     0.0492            768       0.000064017
    Move done                      0.0003     0.0003              2       0.000138592
    New Gradient                   0.1692     0.0022            768       0.000220259
      Determinant                  0.0156     0.0156            768       0.000020272
      OneBodyJastrow               0.0022     0.0022            768       0.000002863
      Single-Particle Orbitals     0.1111     0.1111            768       0.000144617
      ThreeBodyJastrow             0.0122     0.0122            768       0.000015857
      TwoBodyJastrow               0.0259     0.0259            768       0.000033751
    Set active                     0.0536     0.0536            768       0.000069834
    Update                         0.0580     0.0010            404       0.000143605
      Determinant                  0.0209     0.0209            404       0.000051738
      OneBodyJastrow               0.0001     0.0001            404       0.000000210
      ThreeBodyJastrow             0.0155     0.0155            404       0.000038441
      TwoBodyJastrow               0.0205     0.0205            404       0.000050708
  Initialization                   0.0836     0.0836              1       0.083567348
  Pseudopotential                  0.2819     0.0014              2       0.140934426
    Make move                      0.0600     0.0600            960       0.000062481
    Value                          0.2205     0.0029            960       0.000229717
      Determinant                  0.0191     0.0191            960       0.000019882
      OneBodyJastrow               0.0029     0.0029            960       0.000003048
      Single-Particle Orbitals     0.0324     0.0324            960       0.000033763
      ThreeBodyJastrow             0.1493     0.1493            960       0.000155538
      TwoBodyJastrow               0.0139     0.0139            960       0.000014487
```

**Comment by PDoakORNL** [comment]
If you were to put the units of the timing in the output it would make the scientist in me so happy.  I assume s but I feel like every timer I use demands I go look that up. Sometimes ns, sometimes micros, sometimes s.

**Comment by ye-luo** [comment]
In order to extract data, a situation that some runs give me 1.001ms and then some runs give 990us is a disaster.

**Comment by PDoakORNL** [comment]
I just want units somewhere not different ones each run.

**Comment by ye-luo** [comment]
@markdewing Could you put (s) in the column headers?

**Comment by mdewing** [comment]
Adding (s) to the current headers shifts them enough they don't really line up anymore.
```
Stack timer profile
Timer                           Inclusive_time(s)  Exclusive_time(s)  Calls       Time_per_call(s)
Total                              1.8014     1.0995              1       1.801400344
  Diffusion                        0.3365     0.0026              2       0.168253028
    Accept move                    0.0013     0.0013            404       0.000003147
    Current Gradient               0.0022     0.0017            768       0.000002916
```

Possible options:

Remove 'time'
```
Stack timer profile
Timer                           Inclusive (s)  Exclusive (s)  Calls       Time_per_call (s)
Total                              1.8014     1.0995              1       1.801400344
  Diffusion                        0.3365     0.0026              2       0.168253028
    Accept move                    0.0013     0.0013            404       0.000003147
    Current Gradient               0.0022     0.0017            768       0.000002916
```

Put 'time (s)' on another line.
```
Stack timer profile
Timer                           Inclusive    Exclusive      Calls     Time_per_call (s)
                                 time (s)     time (s)
Total                              1.8014     1.0995              1       1.801400344
  Diffusion                        0.3365     0.0026              2       0.168253028
    Accept move                    0.0013     0.0013            404       0.000003147
    Current Gradient               0.0022     0.0017            768       0.000002916
```

**Comment by ye-luo** [comment]
A lazy solution. Change `Stack timer profile` to `Stack timer profile in seconds`. I mean something simple to remind people the unit.

**Comment by mdewing** [comment]
If @PDoakORNL  is okay with it, I like the lazy solution

**Review by ye-luo — APPROVED** [review]
If better looking is needed, we can change it later.

**Comment by PDoakORNL** [comment]
That's all I wanted

**Pull request merged**
