### PR TITLE
Add spline evaluate_v offload

### PR DESCRIPTION
**Pull request by jtkrogel**
The PR implements the evaluate_v routine for splined orbitals following the pattern established by the existing evaluate_vgh implementation.  

Single and multi-threaded checks (via check_spo and check_spo_batched) pass on both oxygen (without offload) and on Summit (with offload).

### CODE REVIEW

**Review by ye-luo — CHANGES_REQUESTED** [review]
Nothing is wrong. Just need to test the CI since this is the first PR on this branch.

**Comment by ye-luo** [comment]
test this please

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
test this please

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
I can't make the CI pass due to #187

**Pull request merged**
