### PR TITLE
Find mkl upgrade

### PR DESCRIPTION
**Pull request by PDoakORNL**
This is a little more robust on my platforms.

### CODE REVIEW

**Comment by mdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
Please update the PR explaining what is your platform and why it is more robust on your platform.

**Comment by ye-luo** [comment]
@PDoakORNL Is this just make miniQMC consistent with QMCPACK?

**Comment by PDoakORNL** [comment]
Yes that's all it does.  Fixed a clang cmake problem for me on oxygen, I think related to mkl include directories not being added. It just failed to "find" Blas/Lapack so I copied this in from QMCPack.

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
