### PR TITLE
Replace 1 nel det with 2 nel/2 dets.

### PR DESCRIPTION
**Pull request by ye-luo**

### CODE REVIEW

**Comment by markdewing** [comment]
I don't like the added complexity from the second determinant, but I think it's necessary to get the matrix size correct (which is important).

**Comment by grahamlopez** [comment]
This is related to a question that I had: I was viewing the matrix update as a O(n^3) algorithm to be dealt with. How important is having this added complexity in the matrix layout(s) to the overall behavior and optimization of the kernel? Does it make enough difference to not be dominated by the O(n^3)?

**Comment by markdewing** [comment]
Given the N^3 complexity, I think it's important to have the relation between the problem size and the matrix size correct.    One matrix of NxN is different than two matrices of N/2xN/2.
If miniqmc has a single matrix of size NxN, I think it would be hard to explain the relationship to the QMCPACK problem size (maybe not hard, just that it would require explaining)

Also, the balance between the N^2 distance table / Jastrow computation with the N^3 work of the matrix will be thrown off if there is one NxN matrix.  In case someone is trying more involved work scheduling with multiple kernels.

**Comment by grahamlopez** [comment]
Thanks, that makes sense.

**Comment by prckent** [comment]
Just to clarify: this is so we have both "upspin" and "downspin" determinants?

**Comment by markdewing** [comment]
Yes, this change adds up and down determinants to the miniapp

**Comment by ye-luo** [comment]
Since our miniQMC needs to represent the actual QMC simulation, it is better to have up/down since the computational cost is very very different as @markdewing pointed out.
I still leave 1 det in the check_determinants for simplicity

**Comment by prckent** [comment]
+1

**Pull request merged**
