### PR TITLE
Only add C++11 flags on XL when not already present

### PR DESCRIPTION
**Pull request by chuckatkins**
Make the addition of std=c++11 conditional on the flags not already being there.

Note that neither this nor the previous code would address the  XL > 13.5 and CMake < 3.11 issue since it fails to detect as XL at all in that case.  This just allows the language standards to be used if they're there with a fallback if they're not.

### CODE REVIEW

**Comment by ye-luo** [comment]
Okay to test

**Review by ye-luo — CHANGES_REQUESTED** [review]
There is no issue with this PR.
I put it on hold because Summit still doesn't have cmake 3.11 as today. Once it is available and I can verify it, this PR will be merged.

**Comment by grahamlopez** [comment]
cmake 3.11.3 is installed on summit-dev and is the default. It will be installed on summit when it is back up and available (not for some several days).

**Review by ye-luo — APPROVED** [review]
Verified on Summit with CMake 3.11.3.

**Pull request merged**
