### PR TITLE
Add unit testing with Catch

### PR DESCRIPTION
**Pull request by mdewing**
Add the Catch include file from QMCPACK.

Add one unit test and a unit test executable.   The design (initially, at least) is to have a single executable for all the unit tests (vs. a test per directory as is done in the main QMCPACK code).

### CODE REVIEW

**Review by PDoakORNL — CHANGES_REQUESTED** [review]
I want a change to put my alternate PR for Catch and unit testing in.  I think all external code should be out of miniqmc/src

**Comment by mdewing** [comment]
Should we create an 'external_codes' directory at the top level, like QMCPACK?

**Comment by PDoakORNL** [comment]
That is what I did. But I also have a working developer modifiable CDash hookup as well. I'd like to get that in at least instead of the inflexible mess we have in QMCPACK.

**Comment by ye-luo** [comment]
@PDoakORNL What is the inflexible mess in QMCPACK, please submit an issue there.

**Pull request closed without merging**
