### PR TITLE
Spurious comma in FindMKL

### PR DESCRIPTION
**Pull request by TApplencourt**
```
-  set(MKL_LINKER_FLAGS "-L${MKL_LINK_DIRECTORIES} -Wl,-rpath,${MKL_LINK_DIRECTORIES}")
+  set(MKL_LINKER_FLAGS "-L${MKL_LINK_DIRECTORIES} -Wl,-rpath ${MKL_LINK_DIRECTORIES}")
```

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by ye-luo** [comment]
It is not clear to me the previous way is wrong and the current way is correct. Please list the accepted ways from different compilers.

**Comment by PDoakORNL** [comment]
From clang command line reference


-Wl,<arg>,<arg2>...
Pass the comma separated arguments in <arg> to the linker

**Comment by ye-luo** [comment]
I checked gnu 6.2 and clang 6.0, I didn't see any issue at linking. Since -Wl is passing command to the linker, I view comma separator a more rigorous way to distinguish if the next term is for the compiler or the linker.

**Comment by PDoakORNL** [comment]
From the IBM XL C/C++ manual

Usage
In the string following the
-W
option, use a comma as the separator for each
option, and do not include any spaces. If you need to include a character that is
special to the shell in the option string, precede the character with a backslash. For
example, if you use the
-W
option in the configuration file, you can use the escape
sequence backslash comma (\,) to represent a comma in the parameter string.

**Comment by ye-luo** [comment]
OK. Talked to @TApplencourt. It is probably a compiler issue not our problem. For any change to the build system, the justification needs to include what platform, compiler and the error.

**Pull request merged**
