### PR TITLE
 Allows changing acceptance ratio via -R. 

### PR DESCRIPTION
**Pull request by ye-luo**
The default value is unchanged 0.5 as before.

### CODE REVIEW

**Comment by prckent** [comment]
What is motivation for adding this option?

Perhaps a wider discussion is needed about what the "fake" QMC in miniqmc is actually doing: VMC w/wo drift, where 50% acceptance is fine, or a fake DMC where the acceptance is 99%+ but we need drift and an "energy" (laplacian) measurement? These are not the same. Since we care about DMC performance more than VMC, are we able to properly capture DMC work?

**Comment by ye-luo** [comment]
The current default fake run is 50% VMC with drift.
I add this option to capture DMC as a 99% VMC with drift.
I think both are important.

**Comment by prckent** [comment]
I would rather our default was fake DMC since this is what we are audited on.

**Comment by ye-luo** [comment]
I don't want to change the default in this PR.
For developing algorithms, assuming 99% is worse than 50%.
Optimization may go into extreme cases.

**Comment by prckent** [comment]
OK.

I prefer something other than -R since there is already -r. Otherwise no objections on this PR.

**Comment by ye-luo** [comment]
I went through the list of arguments. -a, -r have been used already. So I picked -R.

**Comment by prckent** [comment]
Case sensitivity will trip people up. Change -r to something else or pick a different input label for the ratio. Why not -rcut for -r (isn't this the pp cutoff? what is rmax?)

**Comment by ye-luo** [comment]
rmax is for NLPP cutoff. I can change it to -c. I don't know if only a single charactor is allowed.

**Comment by ye-luo** [comment]
rmax is for NLPP cutoff. The current argument handling only allows 1 charactor.
adjusting rmax is a rarely used option. @prckent how about change it to -x and use -r for acceptance ratio?

**Comment by prckent** [comment]
Good with me (-r, -x ).

**Review by prckent — APPROVED** [review]

**Pull request merged**
