### PR TITLE
Kokkos bootcamp 2018 (general groundwork)

### PR DESCRIPTION
**Pull request by ibaned**
These are some changes made during the Kokkos bootcamp which seem general enough to have in QMCPACK proper.

### CODE REVIEW

**Comment by ye-luo** [comment]
miniQMC is not for Kokkos only.
I think all the changes should land on the Kokkos branch but not the main develop unless it is a general algorithmic change.
QMC_RESTRICT and QMC_FORCEINLINE are not necessary.
`-Drestrict=__restrict__` passing to nvcc could work for CUDA.

**Comment by grahamlopez** [comment]
okay to test

**Comment by lshulen** [comment]
There are several of these changes that I feel are general and useful.  For instance, we are targeting performance portability and restrict is NOT available everywhere.  In my opinion, I think it is clearer to make it into an explicit macro like this rather than the -Drestrict gymnastics.  There are a couple of kokkos specific changes in the CMAKE file, but they should not cause any problems if kokkos is not present.  I'm less sure about the omp_get_max_threads stuff, but again, I think it is clearer to have an explicit macro that uses known functionality if it is present (if openmp is being used) but does something else if it is not there.

**Comment by ibaned** [comment]
Just a few supporting facts:
 - Having a `#define QMC_RESTRICT __restrict__` in `config.h` seems cleaner than `-Drestrict=__restrict__`
 - NVCC cannot parse `__forceinline`, hence `QMC_FORCEINLINE`
 - NVCC seems to always include `<omp.h>`, hence redefining `omp_get_XXX` is wrong, hence `qmc_get_XXX`
 - The git subject string sanitization for quotes is generally useful.

Not saying this PR is great as it is, but it is worth considering some of these items.

**Comment by grahamlopez** [comment]
None of this breaks vanilla non-kokkos builds, so I don't have a problem with reducing some fragility.
+1

**Comment by ye-luo** [comment]
1. I don't have much concern on the Kokkos stuff in CMakeLists. PR separately.
2. We had issue on double quotes, is your PR get that fixed? PR separately. We probably will adopt it also on QMCPACK.
3. restrict should be available anywhere but the keyword may be different. Some have underscores. If we have it as macro, it is considered source code. Changing compiler option is better for maintenance than source code. restrict may be performance critical. So defining it as empty even for CUDA is wrong to me.
4.  __forceinline redefine it as inline from compiler options. No need to change source.
5. omp_get_XXX. I don't feel changing all of them is appropriate. We may want to distinguish inside and outside the offload region. A code should be able to mix CUDA and CPU OpenMP. So it is not good to change it globally but gradually and locally when you need them.

**Comment by ye-luo** [comment]
For the omp_get_XXX, it is still not clear to me where is the actual problem.
"NVCC seems to always include `<omp.h>`" If you think, this is the reason for the issue, we need to first understand why and where `<omp.h>` is included.

**Comment by ye-luo** [comment]
For the CMake change for Kokkos. Does the Kokkos CPU with OpenMP build? This justify the CMake change.

**Comment by ibaned** [comment]
`<omp.h>` was actually being included by `src/QMCWaveFunctions/WaveFunction.cpp`, so the better fix is to put `#if defined(ENABLE_OPENMP)` in `src/QMCWaveFunctions/WaveFunction.cpp`.

I think this PR will be separated soon.

**Comment by ye-luo** [comment]
@ibaned Probably just remove that include line?

**Comment by ibaned** [comment]
> Probably just remove that include line?

Yes, that works, even simpler.

**Comment by ibaned** [comment]
Will separate into smaller PRs

**Pull request closed without merging**
