### PR TITLE
Avoid GNU/Clang adding -march on PowerPC.

### PR DESCRIPTION
**Pull request by ye-luo**
As discussed in #86

### CODE REVIEW

**Comment by ye-luo** [comment]
@rcclay try this branch

**Comment by rcclay** [comment]
That works fine and passes all the tests.  Thanks for the more elegant fix!

**Comment by rcclay** [comment]
Sort of inline with what @ibaned suggested.

**Comment by ye-luo** [comment]
Yes. I will leave you guys to set them up.
Add a section
`IF(CMAKE_SYSTEM_PROCESSOR MATCHES "ppc64")`
Do something similar to march.
@rcclay Please approve this PR and once it gets merged. You can continue improving it.

**Pull request merged**
